### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by guneet-coder** [ScriptingClubDelhi/ScriptDump#30]

**Comment by guneet-coder** [comment]
def bubbleSort(arr): 
    n = len(arr) 
    for i in range(n-1): 
        for j in range(0, n-i-1): 
          if arr[j] > arr[j+1] : 
                arr[j], arr[j+1] = arr[j+1], arr[j] 
  arr = [4, 34, 59, 2, 282, 31, 9] 
  
bubbleSort(arr) 
  
print ("Sorted array is:") 
for i in range(len(arr)): 
    print ("%d" %arr[i]),

**Comment by blackcrabb** [comment]
// not considered 
closing this because of same issue
